-- Creare user
ALTER SESSION SET CONTAINER = XEPDB1;

DROP USER goship CASCADE;
CREATE USER goship IDENTIFIED BY parola24;

GRANT CREATE SESSION TO goship;
GRANT CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE, CREATE TRIGGER, CREATE PACKAGE, CREATE FUNCTION TO goship;
GRANT UNLIMITED TABLESPACE TO goship;