CREATE SEQUENCE seq_employee
    START WITH 101 
    INCREMENT BY 1 
    MINVALUE 101 
    MAXVALUE 999 
    NOCACHE 
    NOCYCLE;

CREATE SEQUENCE seq_warehouse
    START WITH 101 
    INCREMENT BY 1 
    MINVALUE 101 
    MAXVALUE 999 
    NOCACHE 
    NOCYCLE;

CREATE SEQUENCE seq_producer
    START WITH 101 
    INCREMENT BY 1 
    MINVALUE 101 
    MAXVALUE 999 
    NOCACHE 
    NOCYCLE;

CREATE SEQUENCE seq_category
    START WITH 101 
    INCREMENT BY 1 
    MINVALUE 101 
    MAXVALUE 999 
    NOCACHE 
    NOCYCLE;

CREATE SEQUENCE seq_product
    START WITH 101 
    INCREMENT BY 1 
    MINVALUE 101 
    MAXVALUE 999 
    NOCACHE 
    NOCYCLE;

CREATE SEQUENCE seq_order
    START WITH 101 
    INCREMENT BY 1 
    MINVALUE 101 
    MAXVALUE 999 
    NOCACHE 
    NOCYCLE;

CREATE SEQUENCE seq_client
    START WITH 101 
    INCREMENT BY 1 
    MINVALUE 101 
    MAXVALUE 999 
    NOCACHE 
    NOCYCLE;

CREATE SEQUENCE seq_invoice
    START WITH 101 
    INCREMENT BY 1 
    MINVALUE 101 
    MAXVALUE 999 
    NOCACHE 
    NOCYCLE;